package com.donghuafun

import com.lagradost.cloudstream3.*
import com.lagradost.cloudstream3.utils.*

class DonghuaFunExtractor : ExtractorApi() {
    override val name = "DonghuaFun Player"
    override val mainUrl = "https://play.donghuafun.com"
    override val requiresReferer = false

    override suspend fun getUrl(
        url: String,
        referer: String?,
        subtitleCallback: (SubtitleFile) -> Unit,
        callback: (ExtractorLink) -> Unit
    ) {
        val m3u8Url = if (url.contains("?url=")) {
            url.substringAfter("?url=")
        } else url

        // 1. Fetch the iframe page first to establish a session and grab cookies.
        var cookieString = ""
        try {
            val iframeResponse = app.get(
                url, 
                headers = mapOf(
                    "User-Agent" to "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
                    "Referer" to "https://donghuafun.com/"
                )
            )
            // Extract the session cookies generated by the proxy player
            cookieString = iframeResponse.cookies.entries.joinToString("; ") { "${it.key}=${it.value}" }
        } catch (e: Exception) {
            // Ignore timeout errors, proceed and try anyway
        }

        // 2. Prepare strict headers mimicking the iframe context, attaching the stolen cookies
        val m3u8Headers = mutableMapOf(
            "User-Agent" to "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
            "Origin" to "https://play.donghuafun.com",
            "Referer" to "https://play.donghuafun.com/", // Target the exact iframe domain
            "Accept" to "*/*"
        )
        
        if (cookieString.isNotEmpty()) {
            m3u8Headers["Cookie"] = cookieString
        }

        // 3. Extract the M3U8 links safely. Assign it to a variable instead of immediately looping.
        val extractedLinks = try {
            M3u8Helper.generateM3u8(
                this.name,
                m3u8Url,
                "https://play.donghuafun.com/",
                headers = m3u8Headers
            )
        } catch (e: Exception) {
            emptyList()
        }

        // 4. Actively check if the helper succeeded. If empty, the server blocked the background scrape.
        // We must fallback to natively passing it to ExoPlayer.
        if (extractedLinks.isNotEmpty()) {
            extractedLinks.forEach(callback)
        } else {
            callback.invoke(
                newExtractorLink(
                    this.name,
                    "DonghuaFun (M3U8)",
                    m3u8Url,
                    ExtractorLinkType.M3U8
                ) {
                    this.quality = Qualities.Unknown.value
                    this.referer = "https://play.donghuafun.com/" 
                    this.headers = m3u8Headers
                }
            )
        }
    }
}
